### ISSUE TITLE
[Misc] General Bugs

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#123]
Here are the intial issues that I found while doing a QA testing pass on my iPhone X.  

- [x] The drag does not work across the entire page as it used to.
- [x] The player loading icon is off center
- [x] The window + player bounderies are no longer respected
- [x] The video (in some instances) load continously.
- [x] The player appears *below* the thumb.  It should appear above correct?
- [ ] ~The values after a reaction show "infinity"~
- [ ] ~Clicking outside the expended view in order to exit does not work.  Instead the mute/unmute logic is triggered. (#122)~
- [ ] ~Native video playback delay (surfaced by Patrick).  I believe Patrick said we need to wait on a iOS patch.~
- [x] "Wrong Password" errors are not cleaned up between opening/closing the login form.

Videos:
Video 1: https://files.slack.com/files-pri/T2BK57X52-FF9FWQE23/download/mov_0001.mp4
Video 2: https://files.slack.com/files-pri/T2BK57X52-FF7S2HLUR/download/mov_0002.mp4
Video 3: https://files.slack.com/files-pri/T2BK57X52-FF8BD3VT5/download/mov_0003.mp4

**Comment by lukeed** [comment]
Removed last item because there's nothing we can do about it. Safari video codec is sluggish.

Also added link to existing issue for volume toggle

**Comment by eudisd** [comment]
👍

**Comment by eudisd** [comment]
Closing this out as there are other issues tracking these already
