### ISSUE TITLE
Hover: Player Positioning

### ISSUE THREAD

**Issue by lukeed** [VIDY/embed.js#126]
Player will appear _under_ your thumb when vlink is near the top of the page. But this doesn't feel consistent / expected. 

Perhaps we need to decrease the "will place under" threshold so that _under_ placements are rarer.

**Comment by eudisd** [comment]
The logic I added here is that if the initial startY position is within 1/3 of the page height, then we should the bottom rendered player.  Else we should the top rendered player.  I've tested this and I think the UX works pretty well
