### ISSUE TITLE
Event: Player remains in Hover mode w/o interaction

### ISSUE THREAD

**Issue by lukeed** [VIDY/embed.js#139]
> ***Original Note:***
> sometimes I can just hold down a few times repeatedly and the vidy bugs out and plays perpetually in small view mode even after I let go

Reported on iOS, but perhaps not limited to iOS.

I suspect https://github.com/VIDY/embed.js/blob/master/src/index.js#L207 is related.

**Comment by eudisd** [comment]
I believe I've reproduced a similar bug, but not sure if it's exactly the same.  Basically, in safari, if the user holds down an a vidy link, that just so happens to also be a anchor link, safari brings up the context menu (native copy/paste dropdown) and then once you exit the context dropdown the vidy player perpetually remains in view until you reload the page.

**Comment by lukeed** [comment]
I haven't seen this – have either of you?

**Comment by eudisd** [comment]
I have not seen this with the repro steps described above.

However, I have seen this with another set of repro steps.

1) Hold down an a vlink that also happens to be a <a /> (in iOS safari)
2) Observe the iOS right-click menu shows up.
3) The video remains on the page for ever.
