### ISSUE TITLE
[Desktop] Inconsistent Expanded Placement

### ISSUE THREAD

**Issue by lukeed** [VIDY/embed.js#15]
When a `.vlink` is hovered & places the video **_under_** the cursor, it'll expand to a position too low on the page.

***Regular/Expected Position***

> This is the middle of the page, and is the case when the mask is _above_ the cursor in "hover-mode". If anything, it's a little too high.

<img width="1295" alt="screen shot 2018-08-27 at 11 32 34 am" src="https://user-images.githubusercontent.com/5855893/44678293-eee28a00-a9ec-11e8-9888-c75767478daf.png">

***Incorrect Position***

> Too close to the bottom of the page, happens when hover-placement is below mouse cursor.

<img width="1290" alt="screen shot 2018-08-27 at 11 28 18 am" src="https://user-images.githubusercontent.com/5855893/44678415-27826380-a9ed-11e8-9daa-f3cd24ea6838.png">

**Comment by eudisd** [comment]
I've seen these when dev tools is open it messes with the position.  Did you have dev tools open by any chance?

**Comment by lukeed** [comment]
Nope. it's just from the mask starting off _under_ the cursor. Its destination coordinates are 200px below where it should be
