### ISSUE TITLE
Improve Thumbnail-To-Video Transition

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#172]
Original comment

> The thumbnail is blinking and jarring right now on initial hold. It’s like it resizes quickly and is the mirror image of the first frame of the actual video. The thumbnail needs to be the exact first frame of the video so its smooth and unnoticeable transition

**Comment by lukeed** [comment]
The demo videos we're using (and that PC is pointing to) are **legacy** videos. They were using some kind of algorithm that produced the "most meaningful" screenshot for the video, which would also double as a stadlone meme.

I just verified this by looking at one of them in detail.

For example, here is the actual thumbnail:

![3708d626103f40b26de9e808979a831fb5fac193b639e74ace4d15845ca41475](https://user-images.githubusercontent.com/5855893/51201473-02659300-18b1-11e9-9633-1120ef3de454.jpg)

And here is the _actual_ first frame:

![dist-pfzvrpyvyl now sh_](https://user-images.githubusercontent.com/5855893/51201488-0e515500-18b1-11e9-8920-af356e55ce9b.png)

**Comment by eudisd** [comment]
@lukeed should we close this as resolved/non-issue per the standup discussion?

**Comment by lukeed** [comment]
I'll leave it open for now until I get the script going to do #186 and this at the same time

**Comment by lukeed** [comment]
@gwil that is the video, play it through & you'll see that the video itself it cutting scene/camera angle almost immediately.
