### ISSUE TITLE
Long hold on a hyperlink brings up the hyperlink sheet

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#176]
Related to: https://github.com/VIDY/embed.js/pull/168

Long hold on a hyperlink brings up the hyperlink sheet

**Comment by gwil** [comment]
Not seeing this on `master` - anyone else? I think it was fixed in #162

**Comment by lukeed** [comment]
Don't see this either. I think PC got the old link?

**Comment by gwil** [comment]
Confirmed with PC that he was using a link before that fix went in last Friday
