### ISSUE TITLE
Outro Animation Improvements

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#182]
> when I tap to get out of enlarged view, the white opacity state stays for too long, the two icons at the top linger too long in their final outro animation (make them animate altogether with the reaction animation outros. Also make the reaction animation outros faster. This whole outro animation should be faster and react more instantly as soon as I tap to exit (the white opacity should fade out the moment the second last reaction icon is about to animate out, so its altogether)

**Comment by gwil** [comment]
Closed in #197
