### ISSUE TITLE
On Hover Timing Improvements

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#185]
> can we make the time it takes for the video to come up a little shorter (I know we have that delay to avoid an accidental pop up of the video as you scroll, but can we still have that prevention and bring down the delay a touch) Right now a light hold results in a pause that feels almost too long before something happens which makes it feel a bit broken since theres not that realtime feedback

**Comment by lukeed** [comment]
See https://github.com/VIDY/embed.js/pull/207#issuecomment-455364803
