### ISSUE TITLE
Mobile: Player position always on top of finger

### ISSUE THREAD

**Issue by gwil** [VIDY/embed.js#198]
For mobile only, player should always be positioned in top position

**Comment by lukeed** [comment]
I don't think this is true or _can be_ true - see #165, #126, and a few others.

There's **zero** room to position the player above your finger at some %-threshold of the screen. Especially here with baby phone, the player barely fills in the viewport as it it.

/cc @eudisd

**Comment by eudisd** [comment]
Yeah, perhaps i'm misunderstanding but Patrick's spec specifically asks for the 'bottom' player to render when the ohHover happens on a vlink at the top inch of the screen

**Comment by lukeed** [comment]
Yeah. Put differently, I will not be able to test/use babyphone anymore if we force top-positioning only.

**Comment by gwil** [comment]
Have been waffling on this UX experience, but iOS lead the way and we discovered it's pointless for the player to be *below* your finger, because well, then you can't see it at all — your finger always blocks it

During `hover` state it should always be on top on mobile (top & bottom is okay for desktop), and when there's no room, the video is just below your finger. While moving your finger down a little bit, the player still rests along the top of the viewport (within bounds) until you move the distance of the player and it begins to move down

@lukeed for baby phone wouldn't you just need to move your finger towards the bottom and the player would mostly stay fixed along the top boundary?

**Comment by lukeed** [comment]
I can't help it if the vlink is at the top of the article & is without vertical header space (which would push the vlink lower). 

You can revisit the screenshots in Slack. Those links are at the top of the page, and I'd have 0 way of viewing that player.

While it's not the preferred positioning (ofc), it's 100% necessary. If iOS is not doing this, it's also a mistake.

**Comment by eudisd** [comment]
I think we should punt on this and come back to it after this sprint/demo.  A lot of work has gone into putting this into place.  I'd rather have a post-demo discussion with LukeGo/Luke/Garrett and Patrick about what we want here exactly.  Like I mentioned earlier, Patrick explicitly asked for this.

**Comment by eudisd** [comment]
Update: spoke to Patrick about this and he noted that AO convinced him of moving away from the finger position.   Sorry guys, I was out of the loop on this one.  However, he also agreed we should punt on this since it's not a bug, and come back to it after the demo release this week.

**Comment by lukeed** [comment]
HARD disagree here, **especially** combined with #132 

If touching a vlink at the top of the page, the entire player (as it's meant to be) will be out of the viewport 😆🤣 to start, and you will have to swipe down just so that you can see half the thing

Arria is spending too much time swizzling

**Comment by eudisd** [comment]
lol

**Comment by gwil** [comment]
I see! There's some confusion here bc yes, those are definitely contradictory!

I just confirmed with Nick/AO that the expected behavior is that it's always positioned above the finger (as discussed in this issue) and that #132 is invalid 🤷‍♂️

**Comment by lukeed** [comment]
Right, so that's still my point. No matter how this integrates with one three two, it is ridiculous.

With 132, your thumb is forced into the center of the video. Without 132, the video starts out of viewport so that it's still above my thumb, which is already at the top of the screen.

**Comment by gwil** [comment]
The motivation here is correct, but the video starting in "bottom" position just doesn't work because when you move around it's always below your finger! vs when you have to move down 200px to see the video

> The purpose here is to teach that movement can happen & is required. Negating 100-200 pixels of movement is awkward & may teach first-time users that nothing happens.
