### ISSUE TITLE
Demarcation indented on multiline phrases

### ISSUE THREAD

**Issue by gwil** [VIDY/embed.js#204]
`.vlink span` got a `padding-left 1.5em` which is applied to every line,

Looked into `::first-line` but is only supported on block elements

<img width="689" alt="screen shot 2019-01-16 at 5 18 08 pm" src="https://user-images.githubusercontent.com/286988/51288845-cadf0f80-19b2-11e9-93f6-757e1187fae4.png">

**Comment by lukeed** [comment]
Demo URL?

**Comment by gwil** [comment]
https://esquiresg.com/louis-vuitton-now-yours-personalisation-service-for-sneakers-and-ready-to-wear/

**Comment by lukeed** [comment]
Closed via #206
