### ISSUE TITLE
Edit-Mode Bugs

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#38]
While in edit mode in the dashboard, if you try to do multiple deletes as well as multiple vidy additions in edit mode, some of the deleteds succeed, while others fail.  Similarly, some of the added vidy's succeed and some of them fail.  There are some errors probably happening there.

**Comment by lukeed** [comment]
What do you mean by fail & succeed? Are you talking about the rendering or the API call?

**Comment by eudisd** [comment]
@lukeed I'll move this to dashboard-embed actually, this is from the API call (which as a result messe up the rendering).

**Comment by eudisd** [comment]
Rel https://github.com/VIDY/dashboard-embed/issues/70
