### ISSUE TITLE
Should Not Allow Adding of Empty Embeds In Edit Mode

### ISSUE THREAD

**Issue by eudisd** [VIDY/embed.js#70]
https://cl.ly/da66858f7a45

**Comment by lukeed** [comment]
This would be a bug on the dashboard side. SDK will send back empty string as soon as you click away from a text selection. Dashboard should only post and update in beds if the `copied` value is truthy.

**Comment by lukeed** [comment]
We can short-circuit the `draw()` command if it did not receive a text length, but this alone is not why those Ben beds are being created. AKA it's not SDK's fault for what we discussed yesterday.

**Comment by eudisd** [comment]
That correct @lukeed.  My intention was that this should be handled in both embed.js and dashboard-embed for completeness.  that is, the dashboard should not allow this, but also the embed.js should not draw empty demarkations like that.
